### ISSUE TITLE
Provide link to term's authoritative source

### ISSUE THREAD

**Issue by andrew2net** [geolexica/tc211-termbase#4]
To implement the functionality ISO-TC211/geolexica.com/issues/31 we need to retrieve links to the standards using Relaton. It should retrieve links while converting termbase.xlsx and put the links into an output YAML file.
```
...
authoritative_source:
      ref: ISO 1087-1:2000, 3.4.9
      link: https://www.iso.org/standard/20057.html
...
```

**Comment by ronaldtse** [comment]
@andrew2net we may want to keep the actual link and metadata of the fetched reference in Relaton YAML files so that the site can utilize more features of Relaton in the future.

**Comment by andrew2net** [comment]
Yes, we can use `Relaton::Db` to store fetched references.

**Comment by ronaldtse** [comment]
@andrew2net agreed!
